// File: lib/firebase_options.dart
// Auto-generated by `flutterfire configure`
// Example for project: inventory-app-monica

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for your project.
///
/// You must call `Firebase.initializeApp(options: DefaultFirebaseOptions.currentPlatform)`
/// before using Firebase.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyD3W-EXAMPLE-KEY-HERE",
    appId: "1:965513866316:web:example123456",
    messagingSenderId: "965513866316",
    projectId: "inventory-app-monica",
    authDomain: "inventory-app-monica.firebaseapp.com",
    storageBucket: "inventory-app-monica.appspot.com",
    measurementId: "G-EXAMPLE1234",
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: "AIzaSyD3W-EXAMPLE-KEY-HERE",
    appId: "1:965513866316:android:exampleabcdef",
    messagingSenderId: "965513866316",
    projectId: "inventory-app-monica",
    storageBucket: "inventory-app-monica.appspot.com",
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: "AIzaSyD3W-EXAMPLE-KEY-HERE",
    appId: "1:965513866316:ios:exampleabcd",
    messagingSenderId: "965513866316",
    projectId: "inventory-app-monica",
    storageBucket: "inventory-app-monica.appspot.com",
    iosBundleId: "com.example.inventoryAppMonica",
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: "AIzaSyD3W-EXAMPLE-KEY-HERE",
    appId: "1:965513866316:ios:exampleabcd",
    messagingSenderId: "965513866316",
    projectId: "inventory-app-monica",
    storageBucket: "inventory-app-monica.appspot.com",
    iosBundleId: "com.example.inventoryAppMonica",
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: "AIzaSyD3W-EXAMPLE-KEY-HERE",
    appId: "1:965513866316:web:example987654",
    messagingSenderId: "965513866316",
    projectId: "inventory-app-monica",
    storageBucket: "inventory-app-monica.appspot.com",
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: "AIzaSyD3W-EXAMPLE-KEY-HERE",
    appId: "1:965513866316:web:example111222",
    messagingSenderId: "965513866316",
    projectId: "inventory-app-monica",
    storageBucket: "inventory-app-monica.appspot.com",
  );
}
